local mod = get_mod("HoldFire")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	allow_rehooking = true,
	reset_function = function()
		get_mod("HoldFire").reset_to_defaults()
	end,
	options = {
		widgets = {
			{
				setting_id = "global_settings",
				type = "group",
				sub_widgets = {
					{
						setting_id = "enable_mod",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "toggle_mod_keybind",
						tooltip = "toggle_mod_keybind_description",
						type = "keybind",
						default_value = {},
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "toggle_mod_enabled",
					},
					{
						setting_id = "toggle_ads_filter_keybind",
						tooltip = "toggle_ads_filter_keybind_description",
						type = "keybind",
						default_value = {},
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "toggle_ads_filter_enabled",
					},
					{
						setting_id = "enable_skitarius_omnissiah_hook",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "purge_weapon_profiles",
						type = "checkbox",
						default_value = false,
					},
				},
			},
			{
				setting_id = "weapon_settings",
				type = "group",
				sub_widgets = {
					{
						setting_id = "load_current_weapon_settings",
						type = "checkbox",
						default_value = false,
						tooltip = "load_current_weapon_settings_description",
					},
					{
						setting_id = "ranged_weapon_selection",
						type = "dropdown",
						default_value = "global_ranged",
						tooltip = "ranged_weapon_selection_tooltip",
						options = {
							{ text = "global_ranged", value = "global_ranged" },
							{ text = "stubrevolver_p1_m1", value = "stubrevolver_p1_m1" },
							{ text = "stubrevolver_p1_m2", value = "stubrevolver_p1_m2" },
							{ text = "shotgun_p1_m1", value = "shotgun_p1_m1" },
							{ text = "shotgun_p1_m2", value = "shotgun_p1_m2" },
							{ text = "shotgun_p1_m3", value = "shotgun_p1_m3" },
							{ text = "shotgun_p2_m1", value = "shotgun_p2_m1" },
							{ text = "shotgun_p4_m1", value = "shotgun_p4_m1" },
							{ text = "shotgun_p4_m2", value = "shotgun_p4_m2" },
							{ text = "shotpistol_shield_p1_m1", value = "shotpistol_shield_p1_m1" },
							{ text = "plasmagun_p1_m1", value = "plasmagun_p1_m1" },
							{ text = "ogryn_thumper_p1_m1", value = "ogryn_thumper_p1_m1" },
							{ text = "ogryn_thumper_p1_m2", value = "ogryn_thumper_p1_m2" },
							{ text = "ogryn_rippergun_p1_m1", value = "ogryn_rippergun_p1_m1" },
							{ text = "ogryn_rippergun_p1_m2", value = "ogryn_rippergun_p1_m2" },
							{ text = "ogryn_rippergun_p1_m3", value = "ogryn_rippergun_p1_m3" },
							{ text = "ogryn_heavystubber_p1_m1", value = "ogryn_heavystubber_p1_m1" },
							{ text = "ogryn_heavystubber_p1_m2", value = "ogryn_heavystubber_p1_m2" },
							{ text = "ogryn_heavystubber_p1_m3", value = "ogryn_heavystubber_p1_m3" },
							{ text = "ogryn_heavystubber_p2_m1", value = "ogryn_heavystubber_p2_m1" },
							{ text = "ogryn_heavystubber_p2_m2", value = "ogryn_heavystubber_p2_m2" },
							{ text = "ogryn_heavystubber_p2_m3", value = "ogryn_heavystubber_p2_m3" },
							{ text = "ogryn_gauntlet_p1_m1", value = "ogryn_gauntlet_p1_m1" },
							{ text = "laspistol_p1_m1", value = "laspistol_p1_m1" },
							{ text = "laspistol_p1_m3", value = "laspistol_p1_m3" },
							{ text = "lasgun_p1_m1", value = "lasgun_p1_m1" },
							{ text = "lasgun_p1_m2", value = "lasgun_p1_m2" },
							{ text = "lasgun_p1_m3", value = "lasgun_p1_m3" },
							{ text = "lasgun_p2_m1", value = "lasgun_p2_m1" },
							{ text = "lasgun_p2_m2", value = "lasgun_p2_m2" },
							{ text = "lasgun_p2_m3", value = "lasgun_p2_m3" },
							{ text = "lasgun_p3_m1", value = "lasgun_p3_m1" },
							{ text = "lasgun_p3_m2", value = "lasgun_p3_m2" },
							{ text = "lasgun_p3_m3", value = "lasgun_p3_m3" },
							{ text = "forcestaff_p1_m1", value = "forcestaff_p1_m1" },
							{ text = "forcestaff_p2_m1", value = "forcestaff_p2_m1" },
							{ text = "forcestaff_p3_m1", value = "forcestaff_p3_m1" },
							{ text = "forcestaff_p4_m1", value = "forcestaff_p4_m1" },
							{ text = "flamer_p1_m1", value = "flamer_p1_m1" },
							{ text = "bolter_p1_m1", value = "bolter_p1_m1" },
							{ text = "boltpistol_p1_m1", value = "boltpistol_p1_m1" },
							{ text = "boltpistol_p1_m2", value = "boltpistol_p1_m2" },
							{ text = "autopistol_p1_m1", value = "autopistol_p1_m1" },
							{ text = "autogun_p1_m1", value = "autogun_p1_m1" },
							{ text = "autogun_p1_m2", value = "autogun_p1_m2" },
							{ text = "autogun_p1_m3", value = "autogun_p1_m3" },
							{ text = "autogun_p2_m1", value = "autogun_p2_m1" },
							{ text = "autogun_p2_m2", value = "autogun_p2_m2" },
							{ text = "autogun_p2_m3", value = "autogun_p2_m3" },
							{ text = "autogun_p3_m1", value = "autogun_p3_m1" },
							{ text = "autogun_p3_m2", value = "autogun_p3_m2" },
							{ text = "autogun_p3_m3", value = "autogun_p3_m3" },
							{ text = "psyker_throwing_knives", value = "psyker_throwing_knives" },
							{ text = "psyker_chain_lightning", value = "psyker_chain_lightning" },
						},
					},
					{
						setting_id = "ads_filter",
						type = "dropdown",
						default_value = "ads_hip",
						options = {
							{ text = "disabled", value = "disabled" },
							{ text = "ads_hip", value = "ads_hip" },
							{ text = "ads_only", value = "ads_only" },
							{ text = "hip_only", value = "hip_only" },
						},
					},
					{
						setting_id = "target_radius",
						type = "numeric",
						default_value = 0.10,
						range = { 0.01, 0.20 },
						decimals_number = 2,
					},
					{
						setting_id = "destructible_radius",
						type = "numeric",
						default_value = 0.10,
						range = { 0.01, 0.20 },
						decimals_number = 2,
					},
					{
						setting_id = "target_elites",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "target_specials",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "target_bosses",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "target_normals",
						type = "checkbox",
						default_value = true,
					},
					{
						setting_id = "target_destructibles",
						type = "checkbox",
						default_value = true,
					},
				},
			},
		},
	},
}
